// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const disableChirpyRed = `-- name: DisableChirpyRed :exec
UPDATE users
SET chirpy_red = FALSE
WHERE id = $1
`

func (q *Queries) DisableChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, disableChirpyRed, id)
	return err
}

const enableChirpyRed = `-- name: EnableChirpyRed :exec
UPDATE users
SET chirpy_red = TRUE
WHERE id = $1
`

func (q *Queries) EnableChirpyRed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, enableChirpyRed, id)
	return err
}
